apiVersion: v1
kind: Secret
metadata:
  name: repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/PedroPabloDomenech-next/taller-kubernetes.git
  username: your-user
  password: ghp_xxx